### ISSUE TITLE
请问Notepad++的版本是多少 我重启时提示dll与当前版本不匹配

### ISSUE THREAD

**Issue by wqingqing** [JetNpp/NppMarkdown#1]

**Comment by JetMeta** [comment]
Sorry, It had not been tested under x64 environment. I use the plugin with notepad++(x86). 
Now I have updated the dll, It can be used with notepad++(x64), at least not crashed at the beginning. Thanks for your report.

My environment : x64 windows 7, notepad++ 7.5.5 (x86/x64).

**Comment by wqingqing** [comment]
好的 谢谢 我的Notepad++的版本有点旧，更新之后就可以正常使用了，非常感谢
